#
# build: docker build -t joustava/ekf -f ./ops/Dockerfile.dev .
# run: docker run -it --rm \ 
#                 -p 4567:4567 \
#                 --mount type=bind,source=$(pwd)/apps,target=/project/apps \
#                 --mount type=bind,source=$(pwd)/src,target=/project/src \
#                 --mount type=bind,source=$(pwd)/tests,target=/project/tests \
#                 --mount type=bind,source=$(pwd)/include,target=/project/include \
#                 --rm joustava/ekf bash
#
FROM archlinux

RUN pacman -Syyu --noconfirm
RUN pacman-db-upgrade
RUN pacman -S --noconfirm git libuv openssl gcc cmake make

WORKDIR /deps

RUN git clone https://github.com/uWebSockets/uWebSockets \
  && cd uWebSockets \
  && git checkout e94b6e1 \
  && mkdir build \
  && cd build \
  && cmake .. \
  && make \ 
  && make install

WORKDIR /project
COPY . .

RUN cmake -S . -B build
RUN cmake --build build

CMD [ "./bin/ExtendedKF_LIB_TESTS" ]



